config/routes.rb
Rails.application.routes.draw do
  get "landing/index"
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "landing#index"

  # OIDC callbacks
  get "auth/hack_club/callback", to: "sessions#hackclub_callback", as: :hackclub_callback

  # Dashboard
  get "dashboard", to: "dashboard#index", as: :dashboard
  resources :teams do
    get :join, on: :collection
    post :join, on: :collection
  end
  delete "logout", to: "sessions#destroy", as: :logout
  post "teams/notes", to: "teams#add_note", as: :teams_notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  note       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  team_id    :string
#
class Note < ApplicationRecord
end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id           :integer          not null, primary key
#  name         :string
#  pairing_code :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  team_id      :string
#  user_id      :integer
#
# Indexes
#
#  index_teams_on_user_id  (user_id)
#
class Team < ApplicationRecord
  has_many :team_users, dependent: :destroy
  has_many :users, through: :team_users
  validates :pairing_code, uniqueness: true, presence: true

  before_validation :generate_pairing_code, on: :create

  private

  def generate_pairing_code
    loop do
      self.pairing_code = SecureRandom.alphanumeric(4).upcase
      break unless Team.exists?(pairing_code: pairing_code)
    end
  end
end

app/models/team_user.rb
# == Schema Information
#
# Table name: team_users
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  team_id    :integer          not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_team_users_on_team_id  (team_id)
#  index_team_users_on_user_id  (user_id)
#
# Foreign Keys
#
#  team_id  (team_id => teams.id)
#  user_id  (user_id => users.id)
#
class TeamUser < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id          :integer          not null, primary key
#  email       :string
#  first_name  :string
#  is_admin    :boolean
#  last_name   :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  identity_id :string
#  slack_id    :string
#
class User < ApplicationRecord
  has_one :team_user, dependent: :destroy
  # has_many :teams, through: :team_users
  has_one :team, through: :team_user
  def admin? = is_admin

  def name = "#{first_name} #{last_name}"

  def make_admin! = update!(is_admin: true)

  def remove_admin! = update!(is_admin: false)

  def has_team? = team.any?

  def self.from_hack_club_auth(auth_hash)
    hca_id = auth_hash.dig("uid")
    return nil unless hca_id

    user = find_or_initialize_by(identity_id: hca_id)

    user.email = auth_hash.dig("info", "email")
    user.first_name = auth_hash.dig("info", "first_name")
    user.last_name = auth_hash.dig("info", "last_name")
    user.slack_id = auth_hash.dig("info", "slack_id")
    user.save!
    user
  end

  def profile_picture = "https://cachet.dunkirk.sh/users/#{slack_id}/r"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  after_action :verify_authorized

  helper_method :current_user, :user_signed_in?
  helper_method :current_team, :user_in_team?

  before_action :authenticate_user!

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    !!current_user
  end

  def current_team
    current_user&.team
  end
  def user_in_team?
    !!current_team
  end

  def authenticate_user!
    unless user_signed_in?
      redirect_to root_path, alert: "login, silly"
    end
  end

  rescue_from Pundit::NotAuthorizedError do |e|
    flash[:error] = "hey, you can't do that!"
    redirect_to root_path
  end

  rescue_from ActiveRecord::RecordNotFound do |e|
    flash[:error] = "oops! looks like we dropped that record in the trash..."
    redirect_to root_path
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController
  def omniauth
    auth = request.env.dig("omniauth.auth")

    user = User.find_or_create_by(identity_id: auth.dig("sub")) do |user|
      user.name = auth.dig("name")
      user.email = auth.dig("email")
      user.slack_id = auth.dig("slack_id")
    end

    session[:user_id] = user.id
    redirect_to root_path, notice: "Successfully logged in :D"
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout "dashboard"
  before_action :authenticate_user!
  skip_after_action :verify_authorized

  def index
    nextup = [{title: "Ship project 2", time:Time.new(2026, 1, 8, 10)}]
    @next_event = nextup.min_by { |event| event[:time] }
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  skip_before_action :authenticate_user!
  skip_after_action :verify_authorized

  def index
    redirect_to dashboard_path if user_signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :omniauth_failure, :hackclub_callback ]

  skip_after_action :verify_authorized

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "cya later!"
  end

  def omniauth_failure
    auth = request.env["omniauth.auth"]
  end

  def hackclub_callback
    auth = request.env["omniauth.auth"]

    if auth.nil?
      redirect_to root_path, alert: "Auth failed D:"
      return
    end

    begin
      @user = User.from_hack_club_auth(auth)
    rescue => e
      Rails.logger.error "Error creating HCA user: #{e.message}"
      redirect_to root_path "something went wrong with auth D:"
      return
    end

    if @user&.persisted?
      session["user_id"] = @user.id
      flash[:success] = "welcome aboard!"
      redirect_to root_path
    else
      Rails.logger.error "Failed to create/update HCA user"
      redirect_to root_path, alert: "uh oh! this shouldn't happen"
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!
  skip_after_action :verify_authorized
  helper_method :current_team, :user_in_team?

  def join
    if request.post?
      team = Team.find_by(pairing_code: params[:team_code])

      if team
        TeamUser.find_or_create_by(user_id: current_user.id).update(team_id: team.id)
        redirect_to teams_path, notice: "Successfully joined team!"
      else
        redirect_to action: :join, alert: "Invalid team code"
      end
    end
  end

  def new
    redirect_to teams_path, alert: "You're already in a team" if user_in_team?
    @team = Team.new
  end

  def create
    if user_in_team?
      redirect_to teams_path, alert: "You're already in a team" and return
    end

    @team = Team.new(team_params)
    @team.user_id = current_user.id

    if @team.save
      TeamUser.find_or_create_by(user_id: current_user.id).update(team_id: @team.id)
      redirect_to teams_path, notice: "Team created successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @team = current_team
    @notes = Note.where(team_id: @team.id)
    unless user_in_team?
      redirect_to join_teams_path
    end
  end

  def add_note
    if request.post?
      Note.create(note: params[:note], team_id: current_team.id)
      redirect_to teams_path, notice: "Note created!"
    end
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper

end

app/views/dashboard/index.htlk.erb
<% content_for :title, "Dashboard" %>

<div class="dashboard-content">
  <h1>Welcome, <%= current_user.name %>!</h1>
  <p>This is your dashboard.</p>
</div>

app/views/dashboard/index.html.erb
<% content_for :title, "Dashboard" %>

<div class="dashboard-content">
  <div class="nextup">
    <h2>Next up:
      <% if @next_event %>
      <span>
        <%= @next_event[:title] %>
        —
        in <%= distance_of_time_in_words(Time.current, @next_event[:time]) %>
        (at <%= @next_event[:time].strftime("%Y-%m-%d %H:%M") %>)
      </span>
      <% else %>
        <span>No more deadlines! Thanks for participating :3</span>
      <% end %>
    </h2>
  </div>

  <h1 class="display mt-4">Welcome, <%= current_user.first_name %>!</h1>
  <% if user_in_team? %>
    <h3><%= current_team.name %></h3>
  <% else %>
  <p>
    You aren't in a team yet :c,
    <span class="funny-link-parent">
      <%= link_to "join", teams_path %>
    </span>
    or
    <span class="funny-link-parent">
      <%= link_to "create one!!", new_team_path %>
    </span>
  </p>
  <% end %>
</div>

<style>
  .nextup {
    background-color: #453B61;
    border-radius: 12px;
    padding: 4px 8px;
    border-left: #FF6161 12px solid;
  }
</style>

app/views/landing/index.html.erb
<h1>Min Speed</h1>
<form action="/auth/hack_club" method="post" data-turbo="false">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <button type="submit">log in with hack club?</button>
</form>

<style>
  :root {
      --sidebar-width: unset !important;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Dinobags" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Dinobags">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <% flash.each do |type, message| %>
      <div class="flash flash-<% type %>">
        <%= message %>
      </div>
      <% end %>
      your team is <%= session[:team_id] %>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Min Speed" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Dinobags">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="with-sidebar">
    <div class="layout-wrapper">
      <%= render "shared/sidebar" %>

      <main class="main-content">
        <% flash.each do |type, message| %>
          <div class="flash flash-<%= type %>">
            <%= message %>
          </div>
        <% end %>

        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/layouts/teams.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for(:title) || "Min Speed" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="application-name" content="Dinobags">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class="with-sidebar">
<div class="layout-wrapper">
  <%= render "shared/sidebar" %>

  <main class="main-content">
    <% flash.each do |type, message| %>
      <div class="flash flash-<%= type %>">
        <%= message %>
      </div>
    <% end %>

    <%= yield %>
  </main>
</div>
</body>
</html>

app/views/shared/_sidebar.html.erb
<nav class="sidebar">
  <img src="/midnight.svg" alt="Midnight Logo" class="sidebar-logo" />

  <div class="sidebar-section mb-4">
    <h3 class="font-bold">Navigation</h3>
    <ul>
      <li><%= link_to "Dashboard", main_app.dashboard_path %></li>
      <li><%= link_to "Team", main_app.teams_path %></li>
    </ul>
  </div>

  <div class="sidebar-section mb-4">
    <h3 class="font-bold">
      Account
      <% if current_user&.admin? %>
          <span class="opacity-50 italic">
            (admin)
          </span>
      <% end %>
    </h3>
    <ul>
      <li><%= link_to "Logout", main_app.logout_path, data: { turbo_method: :delete } %></li>
    </ul>
  </div>

  <% if current_user&.admin? %>
  <!--  <div class="sidebar-section mb-4 sidebar-admin">
      <h3 class="font-bold">Admin</h3>
      <ul>
        <li><%#= link_to "Dashboard", main_app.admin_root_path %></li>
      </ul>
    </div> -->
  <% end %>
</nav>

<style>
    nav.sidebar {
        width: calc(300px - 10px);
        height: calc(100% - 10px);
        position: fixed;
        top: 5px;
        left: 5px;
        padding: 15px;
        overflow: scroll;
    }

    .sidebar-logo {
        width: 100%;
        margin-bottom: 20px;
    }

    .sidebar-section ul li {
        background-color: #f76767;
        border-radius: 12px;
        padding: 2px 10px;
        margin-bottom: 8px;
        list-style: none;
    }

    .sidebar-section ul li * {
        width: 100%;
        display: block;
    }
</style>